Modify leading-zero check in bolt11 decoding
RiverFinancial/bitcoinex pull request #60
Opened 2022-10-18 21:17 UTC by yojoots

bolt11 invoices with a `0` amount explicitly set, e.g. `lnbcrt01pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqdqqnp4q0n326hr8v9zprg8gsvezcch06gfaqqhde2aj730yg0durunfhv66dnh5eqnn4w30z5j59jdxykc077phshmlw5kuzmvd4r5slafnlk7q3grjpy6nvxg9stq4xt58kcr3utla2vz0783x5920vhe0p7md9jspddgapr` are still valid according to `lnd` and other bolt11 decoding tools such as https://lightningdecoder.com/ and https://www.bolt11.org/

However, `Bitcoinex.LightningNetwork.decode` (through the private `parse_hrp` and `calculate_milli_satoshi` functions) will result in an `{:error, :amount_with_leading_zero}` instead of decoding 0-amount invoices as expected.

Instead of pattern matching against a leading "0" this update has `calculate_milli_satoshi` perform the following check:

```
    if String.length(amount_str) > 1 and String.starts_with?(amount_str, "0") do
      {:error, :amount_with_leading_zero}
    else
      <EXISTING LOGIC>
    end
```

This should still prevent `amount`s that are more than just "`0`" from being interpreted as valid.

2022-10-19 03:09 UTC, bruteforcecat commented
Thank you for working on this. Can you add a test case for it?

2022-10-19 21:14 UTC, yojoots commented
> Can you add a test case for it?

Good idea, just added one. It fails on `master` (as expected) but succeeds on this branch.

2022-10-21 05:25 UTC, SachinMeier requested changes
I suggest adding the following test case to test for bitcoin amount parsing as well. Otherwise tACK

```elixir
# Amount is 1 bitcoin to test no-multiplier parsing
      {
        "lnbcrt11p34y28ypp5z4tvam0qzsj6eq7adedy2p0ga2lam4jc3g6kn702t9mj6xyldj6qdqqcqzpgxqyz5vqsp55gkl87n3n8qwqadwrt3gfxcdsls8mk2cv5vgh3v8ujexglxpkv9q9qyyssqjx0f3dgylw8dyhy8z6e4ta3pzg09j90uwhd747fsclx5enjalmprnt583744v683prj48xgc57gumzs2406l5m7jqrem3aewh6nzfkspz9m2px",
        %Invoice{
          network: :regtest,
          destination: "02d60dfe3850d115fdb2114b14396d4d2924a25dafc69098d10841e4474d9977dd",
          payment_hash: "1556ceede01425ac83dd6e5a4505e8eabfddd6588a3569f9ea59772d189f6cb4",
          amount_msat: 100_000_000_000,
          timestamp: 1_666_328_804,
          expiry: 86_400,
          description: "",
          min_final_cltv_expiry: 40
        }
      }
```

2023-01-17 02:02 UTC, SachinMeier approved these changes
LGTM

2023-01-17 02:39 UTC, merged